# --- Imprime instrucciones ---

print(f"La suma de 3+2 es =",{3+2})
print("\n")
print(f"La resta de 3-2 es =",{3-2})
print("\n")
print(f"La Multiplicación de 3x2 es =",{3*2})
print("\n")
print(f"La division de 3/2 es =",{3/2})
print("\n")
print(f"La multiplicacion exponencial de 3x2 es =",{3**2})
print("\n")
print(f"El modulo de 3%2 es =",{3%2})    
print("\n")
print(f"El redondeo bajo de 3//2 es =",{3//2})